version: '3.9'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    volumes:
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
