// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	Username          string  `json:"username"`
	FullName          string  `json:"full_name"`
	Email             string  `json:"email"`
	PasswordChangedAt *string `json:"password_changed_at,omitempty"`
	CreatedAt         *string `json:"created_at,omitempty"`
	Image             *string `json:"image,omitempty"`
}

type UserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
}
